-- Mavjud DB ga yangi ustunlar (migration)
ALTER TABLE users ADD COLUMN IF NOT EXISTS phone         VARCHAR(20);
ALTER TABLE users ADD COLUMN IF NOT EXISTS latitude      DOUBLE PRECISION;
ALTER TABLE users ADD COLUMN IF NOT EXISTS longitude     DOUBLE PRECISION;
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_registered BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_blocked    BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_admin      BOOLEAN DEFAULT FALSE;

ALTER TABLE transactions ADD COLUMN IF NOT EXISTS currency        VARCHAR(5) NOT NULL DEFAULT 'UZS';
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS amount_original DOUBLE PRECISION;
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS updated_at      TIMESTAMP DEFAULT NOW();
